/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Odev_01;

import static java.awt.Frame.NORMAL;
import static java.awt.image.ImageObserver.ERROR;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.util.Date;
import java.util.Scanner;
import java.util.concurrent.Delayed;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import java.util.concurrent.TimeUnit;

/**
 * @file Menu
 * @description Java Swing kodlarının bulunduğu kısımdır. Sistemin çalışıp
 * durdurulması gibi işlemler burada yapılmıştır.
 * @assignment Odev -1-
 * @date 10/12/2020
 * @author Muhammet Furkan ÖZEN muhammetfurkan.ozen@stu.fsm.edu.tr
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }
    Kuyruk kuyruk = new Kuyruk();
    static boolean isWorking = false;
    static boolean isDone = false;
    int toplamSure_0, toplamSure_1, toplamSure_2;                               // İstatistik kısmında toplam süreleri göstermek için değişkenler
    String istatistik_0, istatistik_1, istatistik_2 = "";                       // İstatistik kısmındaki isimleri göstermek için değişken

    public static void DosyaOlustur(String URL) {
        File f = new File(URL);
        try {
            if (!f.exists()) {                                                  // eğer dosya yoksa
                f.createNewFile();                                              // dosyayı oluşturur.
                System.out.println(f.getName() + " adlı dosya oluşturuldu...");

            } else {
                System.out.println("Dosya halihazırda var, oluşturma işlemi başarısız...");
            }
        } catch (IOException e) {                                               // hata yakalama
            // TODO: handle exception
            e.printStackTrace();
        }
    }

    public static void DosyaSil(String URL) {
        File f = new File(URL);

        if (f.exists()) {                                                       // eğer dosya varsa
            f.delete();                                                         // dosyamızı siliyoruz.
            System.out.println(f.getName() + " adlı dosya silindi...");
        } else {
            System.out.println("Dosya bulunamadı, silme işlemi başarısız...");
        }
    }

    public static void DosyaYazma(String URL, String ad, int oncelik, int sure) {
        File file = new File(URL);                                              // hangi dosya üzerinde işlem yapacağımızı seçiyoruz.
        ad = ad.replace(" ", "");                                               //BOŞLUKLARI SİLME
        try {
            FileOutputStream fos = new FileOutputStream(file, true);
            BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(System.out));
            writer.newLine();
            String[] words = ad.split(" ");
            for (String word : words) {
            }
            String yazi = ad + "#" + oncelik + "#" + sure + "\n";               // İstediğimiz formattaki yazıyı String yazi'ya atıyoruz.

            fos.write(yazi.getBytes());
            fos.flush();
            fos.close();
        } catch (FileNotFoundException e) {
// TODO Auto-generated catch block
            e.printStackTrace();
        } catch (IOException e) {
// TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnDosyaOku = new javax.swing.JButton();
        jbtnVezneCalisiyor = new javax.swing.JButton();
        jLabelOncelikliKuyrukYapisi = new javax.swing.JLabel();
        jbtnBankaKapandi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaUst = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtAreaVezneAnlik = new javax.swing.JTextArea();
        jtxtMusteriAdSoyad = new javax.swing.JTextField();
        jtxtOncelik = new javax.swing.JTextField();
        jtxtSure = new javax.swing.JTextField();
        jbtnEkle = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtAreaMusteriGecmis = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxtAreaIstatistik = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 700));

        jbtnDosyaOku.setText("Dosya Oku");
        jbtnDosyaOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDosyaOkuActionPerformed(evt);
            }
        });

        jbtnVezneCalisiyor.setText("Vezne Calisiyor");
        jbtnVezneCalisiyor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVezneCalisiyorActionPerformed(evt);
            }
        });

        jLabelOncelikliKuyrukYapisi.setText("Oncelikli Kuyruk Yapısı");

        jbtnBankaKapandi.setText("Banka Kapandi");
        jbtnBankaKapandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBankaKapandiActionPerformed(evt);
            }
        });

        jtxtAreaUst.setColumns(20);
        jtxtAreaUst.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaUst);

        jLabel2.setText("Vezne (Anlik Islem Goren Musteri)");

        jLabel3.setText("Musteri Ekle");

        jLabel4.setText("Vezne Musteri Gecmisi");

        jtxtAreaVezneAnlik.setColumns(20);
        jtxtAreaVezneAnlik.setRows(5);
        jScrollPane2.setViewportView(jtxtAreaVezneAnlik);

        jtxtMusteriAdSoyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMusteriAdSoyadActionPerformed(evt);
            }
        });

        jbtnEkle.setText("Ekle");
        jbtnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEkleActionPerformed(evt);
            }
        });

        jLabel5.setText("Musteri Ad_soyad");

        jLabel6.setText("Oncelik");

        jLabel7.setText("Sure");

        jtxtAreaMusteriGecmis.setColumns(20);
        jtxtAreaMusteriGecmis.setRows(5);
        jScrollPane3.setViewportView(jtxtAreaMusteriGecmis);

        jLabel8.setText("Musterinin Onceliklere Gore Istatistigi");

        jtxtAreaIstatistik.setColumns(20);
        jtxtAreaIstatistik.setRows(5);
        jScrollPane4.setViewportView(jtxtAreaIstatistik);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addComponent(jbtnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jtxtOncelik, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jtxtMusteriAdSoyad, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jtxtSure, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(126, 126, 126))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jbtnDosyaOku)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnVezneCalisiyor)
                                .addGap(58, 58, 58)
                                .addComponent(jLabelOncelikliKuyrukYapisi)
                                .addGap(69, 69, 69)
                                .addComponent(jbtnBankaKapandi)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDosyaOku)
                    .addComponent(jbtnVezneCalisiyor)
                    .addComponent(jLabelOncelikliKuyrukYapisi)
                    .addComponent(jbtnBankaKapandi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtMusteriAdSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtOncelik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtSure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jbtnEkle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEkleActionPerformed
        DosyaOlustur("musteri.txt");
        DosyaYazma("musteri.txt", jtxtMusteriAdSoyad.getText(), Integer.parseInt(jtxtOncelik.getText()), Integer.parseInt(jtxtSure.getText()));
        Thread t1 = new Thread();
        if (isWorking == true) {
            kuyruk.addLast(jtxtMusteriAdSoyad.getText(), Integer.parseInt(jtxtSure.getText()), Integer.parseInt(jtxtOncelik.getText()));
            jtxtAreaUst.setText(kuyruk.printUst());
        }
        t1.start();

    }//GEN-LAST:event_jbtnEkleActionPerformed

    private void jtxtMusteriAdSoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMusteriAdSoyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMusteriAdSoyadActionPerformed

    private void jbtnDosyaOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDosyaOkuActionPerformed
        DosyaSil("kalanMusteri.txt");
        DosyaSil("gunlukIslem.txt");
        JFileChooser chooser = new JFileChooser();
        Scanner in = null;
        String sonucAd = null, sonucOncelik = null, sonucSure = null;
        int sayac = 0, satirAtlamaSayaci = 0;

        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            try {
                in = new Scanner(selectedFile);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            int lineNumber = 1;
            final int donguSayac = 50;
            while (in.hasNextLine() && lineNumber <= donguSayac) {
                //result ="";
                String line = in.nextLine();
                //System.out.println(lineNumber + " + " + line);
                lineNumber++;

                String[] arrSplit = line.split("#");
                sayac = 0;
                for (String arrSplit1 : arrSplit) {
                    //result+=arrSplit1;
                    //System.out.println(arrSplit1);
                    if (sayac == 0) {                                           //isim, öncelik ve süreyi parçalara ayırıyoruz.
                        sonucAd = arrSplit1;
                    } else if (sayac == 1) {
                        sonucOncelik = arrSplit1;
                    } else {
                        sonucSure = arrSplit1;
                    }
                    sayac++;
                }
                System.out.println("Sonuc Ad : " + sonucAd + " Sonuc Sure: " + sonucSure + " Sonuc Oncelik: " + sonucOncelik);

                kuyruk.addLast(sonucAd, Integer.parseInt(sonucSure), Integer.parseInt(sonucOncelik));

//                if (satirAtlamaSayaci++%5 == 4)             // Anlik müşteri gösterilen (no :2) textArea'da 
//                    jtxtAreaUst.append("\n");               // 5 Müşteri yazildiktan sonra alt satıra geçilecek
            }
            jtxtAreaUst.setText(kuyruk.printUst());

            if (in.hasNextLine()) {
                System.out.println("...");
            }
        }
        kuyruk.print();
    }//GEN-LAST:event_jbtnDosyaOkuActionPerformed

    void work(boolean isWorking) {

        while (isWorking == true) {
            System.out.println("Vezne Calisiyor...");

            if (isWorking != true) {
                break;
            }
        }

    }

    private void jbtnVezneCalisiyorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVezneCalisiyorActionPerformed

        //jtxtAreaMusteriGecmis.setText("");
        isWorking = true;
        toplamSure_0 = toplamSure_1 = toplamSure_2 = 0;
        DosyaOlustur("gunlukIslem.txt");

        Thread t = new Thread() {
            @Override
            public void run() {
                try {

                    Thread.sleep(0000);

                    while (isWorking == true && isDone == false) {

                        //-------------------
                        System.out.println("Vezne Calisiyor...");
                        jtxtAreaUst.setText(kuyruk.printUst());                 //Her 2 sn de bir üst area güncellenecek...
                        jtxtAreaVezneAnlik.setText("[(" + kuyruk.anlikNode().oncelik + ") (" + kuyruk.anlikNode().getAd_soyad() + " - " + kuyruk.anlikNode().sure + ")]");

                        if (kuyruk.anlikNode().oncelik == 0) {
                            istatistik_0 += kuyruk.anlikNode().ad_soyad + ", ";
                        } else if (kuyruk.anlikNode().oncelik == 1) {
                            istatistik_1 += kuyruk.anlikNode().ad_soyad + ", ";
                        } else if (kuyruk.anlikNode().oncelik == 2) {
                            istatistik_2 += kuyruk.anlikNode().ad_soyad + ", ";
                        }

                        if (kuyruk.anlikNode().sure > 40000) {                  //40 sn den fazla ise içeri girip işlemleri yap
                            DosyaYazma("gunlukIslem.txt", kuyruk.anlikNode().ad_soyad, kuyruk.anlikNode().oncelik, 40000);
                            if (kuyruk.anlikNode().oncelik == 0) {
                                toplamSure_0 += 40000;
                            } else if (kuyruk.anlikNode().oncelik == 1) {
                                toplamSure_1 += 40000;
                            } else if (kuyruk.anlikNode().oncelik == 2) {
                                toplamSure_2 += 40000;
                            }

                            jtxtAreaMusteriGecmis.append("[(" + kuyruk.anlikNode().oncelik + ")(" + kuyruk.anlikNode().ad_soyad + "-" + 40000 + ")]- vezneye geldi, 40 sn hizmet aldı ve kuyruğun sonuna eklendi.\n");
                            kuyruk.anlikNode().sure -= 40000;
                            kuyruk.addLast(kuyruk.anlikNode().ad_soyad, kuyruk.anlikNode().sure, kuyruk.anlikNode().oncelik);
                            kuyruk.remove();

                            //kuyruk.print();
                        } else {                                                // 40 sn den az ise içeri girip işlemleri yap.
                            DosyaYazma("gunlukIslem.txt", kuyruk.anlikNode().ad_soyad, kuyruk.anlikNode().oncelik, kuyruk.anlikNode().sure);
                            if (kuyruk.anlikNode().oncelik == 0) {
                                toplamSure_0 += kuyruk.anlikNode().sure;
                            } else if (kuyruk.anlikNode().oncelik == 1) {
                                toplamSure_1 += kuyruk.anlikNode().sure;
                            } else if (kuyruk.anlikNode().oncelik == 2) {
                                toplamSure_2 += kuyruk.anlikNode().sure;
                            }

                            jtxtAreaMusteriGecmis.append("[(" + kuyruk.anlikNode().oncelik + ")(" + kuyruk.anlikNode().ad_soyad + "-" + kuyruk.anlikNode().sure + ")]- vezneye geldi, " + (float) kuyruk.anlikNode().sure / 1000 + " sn hizmet aldı ve vezneden ayrildi.\n");
                            kuyruk.remove();
                        }

                        //-------------------
                        try {
                            TimeUnit.SECONDS.sleep(2);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        if (isWorking != true) {
                            break;
                        }

                    }
                    if (kuyruk.anlikNode() == null) {
                        jbtnBankaKapandi.doClick();
                    }

                } catch (InterruptedException e1) {
                    e1.printStackTrace();
                }

            }
        };

        System.out.println("Vezne Calısıyor Butonuna Tiklandi...");

        t.start();
        System.out.println("");

    }//GEN-LAST:event_jbtnVezneCalisiyorActionPerformed

    private void jbtnBankaKapandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBankaKapandiActionPerformed
        System.out.println("Vezne Kapandi Butonuna Tiklandi...");
        isWorking = false;
        isDone = true;
        work(isWorking);

        DosyaOlustur("kalanMusteri.txt");
        while (kuyruk.anlikNode() != null) {
            DosyaYazma("kalanMusteri.txt", kuyruk.anlikNode().ad_soyad, kuyruk.anlikNode().oncelik, kuyruk.anlikNode().sure);
            kuyruk.remove();
        }
        jtxtAreaIstatistik.append("Oncelik değeri 0 olan musterilerin vezneden hizmet alma durumlari; \n" + istatistik_0 + "\nToplam Vezne Sureleri = " + toplamSure_0 + " sn\n\n");
        jtxtAreaIstatistik.append("Oncelik değeri 1 olan musterilerin vezneden hizmet alma durumlari; \n" + istatistik_1 + "\nToplam Vezne Sureleri = " + toplamSure_1 + " sn\n\n");
        jtxtAreaIstatistik.append("Oncelik değeri 2 olan musterilerin vezneden hizmet alma durumlari; \n" + istatistik_2 + "\nToplam Vezne Sureleri = " + toplamSure_2 + " sn");

    }//GEN-LAST:event_jbtnBankaKapandiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelOncelikliKuyrukYapisi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtnBankaKapandi;
    private javax.swing.JButton jbtnDosyaOku;
    private javax.swing.JButton jbtnEkle;
    private javax.swing.JButton jbtnVezneCalisiyor;
    private javax.swing.JTextArea jtxtAreaIstatistik;
    private javax.swing.JTextArea jtxtAreaMusteriGecmis;
    private javax.swing.JTextArea jtxtAreaUst;
    private javax.swing.JTextArea jtxtAreaVezneAnlik;
    private javax.swing.JTextField jtxtMusteriAdSoyad;
    private javax.swing.JTextField jtxtOncelik;
    private javax.swing.JTextField jtxtSure;
    // End of variables declaration//GEN-END:variables
}
